Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
AllCops:
  Exclude:
   - db/**/*
   - Rakefile
   - bin/**/*
   - config/**/*
   - Gemfile
   - spec/spec_helper.rb
   - spec/rails_helper.rb
   - vendor/**/*
   - script/**/*
