language: ruby
rvm:
  - 2.5.3

services:
  - postgresql

branches:
  only:
    - master

before_script:
  - psql -c 'create database travis_ci_test' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rails db:create db:migrate

script:
  - bundle exec rubocop
  - bundle exec rspec spec
