version: '3.7'
services:
  db:
    image: postgres:9.6
  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/var/www/docflow
    ports:
      - '3000:3000'
    depends_on:
      - db
