version: '3.7'
services:
  db:
    image: postgres:9.6
  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    volumes:
      - .:/var/www/docflow
    ports:
      - '3000:3000'
    depends_on:
      - db
