# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e2eb07857bd0b75f312e39a88f1041dd29671e164e461a3a13f82419779d750f68f18b72aa1b2779cb2b178a72a2f619b725742c52ed0f3c017c6e5fed1c08c

test:
  secret_key_base: b77bdf2ffcf2646fcc6ed22d8c00beed916eb5ee7b02d095944e355299c74969cce092e562363f6e565b96c3615fda3b976b50bcc205cf9cedf1f4a770433983

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
